### ISSUE TITLE
Fix homebrew distribution for Catalina

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2011]
### Description
We've seen lots of cryptic and confusing errors around installing dbt on macOS Catalina since that OS version launched a little more than a month ago. Most of these issues seem to be related to the use of libssl bindings in the snowflake and pg/redshift dbt plugins.

I don't know enough about how homebrew works or macOS system libs (yet), but it appears to me that homebrew-dbt could be doing something differently to make installations on macOS more seamless.

See [this discussion](https://github.com/dotnet/cli/issues/3964#issuecomment-236493536) for some interesting ideas. Which, if any of these, are tractable ideas for us to pursue:
- try the `install_name_tool` approach shown in the link above
- automate one of the approaches shown at the bottom of [this thread](https://forums.developer.apple.com/thread/119429) (it has appeared to fix things for users, but I'm unsure if mucking with symlinks is a good idea (it probably isn't))
- package libssl with the dbt distribution? Is this even a statement that makes sense?

I think the next steps are for me to do some more reading, and for someone with more knowledge of macOS and linked libraries to follow up with some ideas / thoughts / approaches. For now though, wanted to get this topic in writing somewhere.

**Comment by drewbanin** [comment]
@cmcarthur do you recall if we addressed this issue in the latest formula for homebrew-dbt?

**Comment by beckjake** [comment]
One of the things homebrew's `brew audit` suggested, and I implemented in #2119, is setting a version for openssl (`depends_on "openssl@1.1"`). I'm intrigued to see if that fixes it...

**Comment by drewbanin** [comment]
I'm adding this to Octavius Catto in case any action is required, but I do think/hope those changes in #2119 should address this issue

**Comment by beckjake** [comment]
Unfortunately, it seems that users are still experiencing this on macos catalina with dbt 0.16.0.
