### ISSUE TITLE
Is the "sources" key still supported in the dbt_project.yml?

### ISSUE THREAD

**Issue by sgoley** [fishtown-analytics/dbt#2655]
## System info:
Platform: Windows 10.0.18363, Build 18363
dbt: 017.1

## Description:
Running `dbt compile` when `dbt_project.yml` includes a `sources:` key in same style as the documentation page: 
https://docs.getdbt.com/reference/source-configs#examples

Resulting error:
```
Running with dbt=0.17.1
Encountered an error while reading the project:
  ERROR: Runtime Error
  at path []: Additional properties are not allowed ('sources' was unexpected)     

Error encountered in <local_dir>\<dbt_dir>\dbt_project.yml
Encountered an error:
Runtime Error
  Could not run dbt
```

## Expected Result: 

Having the following within the project should disable the usage of the source, not throw an error:

```
sources:
  events:
    clickstream:
      +enabled: false
```

**Comment by jtcohen6** [comment]
I was able to reproduce this error locally by running a project with:
* dbt v0.17.1
* `dbt_project.yml` config-version 1 syntax

Having `sources` defined as a top-level key in `dbt_project.yml` works with either:
* dbt<=0.16.1 + config-version 1
* dbt>=0.17.0 + config-version 2

That is to say, the bug here is around our attempt to offer a smooth path for users who want to upgrade to v0.17 without needing to [migrate](https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-0-17-0/#a-new-dbt_projectyml-config-version) their `dbt_project.yml` file from config-version 1 to 2 right away. Ideally, (a) dbt would gracefully handle this error, or at least (b) give a clearer error message. Sorry for the confusion there.

Could you try adding `config-version: 2` to your `dbt_project.yml` file and confirm that this specific error disappears?

Since we're planning to drop support for `config-version: 1` in one of the next minor versions, I don't think we'll prioritize a fix here. I'll leave the issue open in case a community member wants to contribute the fix—and I'm glad it now exists, for anyone who runs into the same confusing error. Thanks @sgoley!

**Comment by sgoley** [comment]
Thanks @jtcohen6! The `config-version: 2` resolves the error. 

As a note, a lot of the current packages (e.g. `dbt-utils`) are all built under `config-version: 1`. Will dropping support for that config version break those package imports / usage?

![image](https://user-images.githubusercontent.com/10283176/88812579-e28d7b80-d185-11ea-9f61-46e7ef9e4922.png)

**Comment by jtcohen6** [comment]
Yes, the dbt version that officially drops support for version-1 project configs will be incompatible with older package versions.

We've released new versions of all Fishtown-maintained packages to use `config-version: 2`. For instance, you should be able to upgrade `dbt_utils` to any version [>=0.4.0](https://github.com/fishtown-analytics/dbt-utils/releases/tag/0.4.0). As far as community-supported packages such as `postgres_utils`, I hope the maintainers have released a newer version, or that they will release one soon.

**Comment by sgoley** [comment]
Ty for the suggestion. 

Updated in package and re-released: 
https://github.com/sgoley/dbt-postgres-utils/releases/tag/0.0.2

I'm happy to close this as "wontfix" but is it your convention to leave open since the bug wasn't resolved?

**Comment by jtcohen6** [comment]
Oh sorry! I had completely forgotten that you're the maintainer, and didn't mean to come off as strongly hinting above. I just checked hubcap and indeed now see you there: https://github.com/fishtown-analytics/hubcap/pull/4

In any case, thanks for releasing a new version :)

I'll leave the issue open for a bit, in case it strikes the fancy of a community contributor, since I don't imagine the change to be fiendishly complex.

**Comment by jtcohen6** [comment]
I'm going to close this issue, since v0.19.0 officially deprecates the `config-version: 1` format of `dbt_project.yml`. This bug only appears for projects running v0.17 or v0.18 with version-1 config.
